const dataInfo = {
    'english':{
        'about_us':'About us',
        'donate':'Donate',
        'forecast':'Forecast of Russian losses for the next 12 months',
        'forecastP':'*The forecast is developed on the basis of the statistics of the General Staff of the Armed Forces of Ukraine for the last 5 weeks',
        'alive':'Still alive',
        'dead':'Dead',
        'wounded':'Severaly wounded',
        'totalnumber':'The total number of',
        'popupPfirst':'*Data on the total number of Russian military equipment are taken from open sources "name" and include: preserved in warehouses, including weapons, etc.',
        'popupPsecond':'**Data on the number of military assets that were in service with the Russian Armed Forces at the beginning of the full-scale invasion are taken from the "name"',
        'soldiersRus':'Personnel units',
        'monthstatistic':'Monthly statistics',
        'dataHeadoffice':'*On the basis of the statistics of the General Staff of the Armed Forces of Ukraine',
        'groundtarget':'Ground targets',
        'weekstatistic':'Weekly statistics',
        'dataheadofficeweeks':'*On the basis of the statistics of the General Staff of the Armed Forces of Ukraine for the last 12 weeks',
        'aviation':'UAV systems',
        'ourproject':'Our project "StatsWar" was created so that all the scales of the catastrophe called "Russian war of occupation 2022" against the people of Ukraine would be recorded FOREVER.',
        'statdata':'Statistics, data, analytics and forecasting on our resource are somewhat unique. Our team aims to process the maximum number of important statistics and make the most understandable analysis of this war for the average user.',
        'updates':'In further updates of the resource, data and statistics about this war will be expanded and lighten necessarily.',
        'support':'Support the project here',
        'contacts':'Contacts',
        'email':'statswar@gmail.com',
        'tanks':'Tanks',
        'armmachines':'AFVehicles',
        'artilery':'Artillery systems',
        'rszo':'MLRS',
        'planes':'Fighter planes',
        'helicopters':'Helicopters',
        'PPO':'ATGM/SRBM systems',
        'rockets':'Cruise missiles',
        'autotechnicks':'Automotive equip',
        'specialtech':'Special military equip',
    },
    'ukrainian':{
        'about_us':'Про нас',
        'donate':'Задонатити',
        'forecast':'Прогноз втрат рф на наступні 12 місяців',
        'forecastP':'*Прогноз розроблений на основі статистики останніх 5 тижнів Генштабу ЗСУ',
        'alive':'Живі',
        'dead':'Мертві',
        'wounded':'Важко поранені',
        'totalnumber':'Загальна кількість',
        'popupPfirst':'*Дані загальної кількості військових засобів рф взяті з відкритих джерел “назва” та включають в себе: законсервовані на складах, включно на озброєнні, тощо.',
        'popupPsecond':'**Дані кількості військових засобів, які перебували на озброєнні ЗС рф на початок повномаcштабного вторгнення взято з “назва”',
        'soldiersRus':'Військові РФ',
        'monthstatistic':'Помісячна статистика',
        'dataHeadoffice':'*На основі даних статистики Генштабу ЗСУ',
        'groundtarget':'Наземні цілі',
        'weekstatistic':'Тижнева статистика',
        'dataheadofficeweeks':'*На основі даних статистики Генштабу ЗСУ за останні 12 тижні',
        'aviation':'Авіація, БПЛА, ракети',
        'ourproject':' Наш проект "StatsWar" створений, щоб всі катастрофи під назвою "російська окупаційна війна 2022" проти народу України були зафіксовані НАЗАВЖДИ.',
        'statdata':'Статистика, дані, аналітика та прогнозування на нашому ресурсі є в дечому унікальні. Наша команда має за мету опрацювати максимальну кількість важливої статистики та зробити максимально зрозумілий аналіз цієї війни для Вас.',
        'updates':'В Подальших оновленнях ресурсу дані та статистика про цю війну будуть розширюватись.',
        'support':'Підтримати проект тут',
        'contacts':'Контакти:',
        'email':'statswar@gmail.com',
        'tanks':'Танки',
        'armmachines':'ББМашини',
        'artilery':'Артилерія',
        'rszo':'РСЗВ',
        'planes':'Бойові літаки',
        'helicopters':'Гелікоптери',
        'PPO':'ППО/ЗРК',
        'rockets':'Крилаті ракети',
        'autotechnicks':'Автомобільна техніка',
        'specialtech':'Спецтехніка',
    },
};
export{dataInfo}
